name: install_dependencies
run-name: Install dependencies

on:
  workflow_dispatch:

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Install dependencies
        shell: bash # stops windows hosts from using powershell
        run: |
          pip install poetry pytest
          poetry install --no-interaction --no-root -vvv --all-extras
          poetry install --no-interaction --no-root --all-extras -vvv
          pip install wheel
          pip install --upgrade setuptools
          pip install --editable ".[test,ml,medical,dev, ocv]"
