name: format
run-name: Format

on:
  workflow_call:
    inputs:
      files:
        description: "Files to check formatting of"
        required: true

jobs:
  runs-on: ubuntu-latest
  lint:
    - name: Check out source repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Black check
      uses: psf/black@stable
      with:
        options: "--check --no-color"
        src: ${{ github.event.inputs.files }}}
