name: pull_request
run-name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    
    
# Prevent running concurrently
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
      
jobs:

  #Check format of code
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Format code
        # Lints and formats are called only against the changed files, because other
        # files must have come from master
        run: bash deploy/format.sh ${{ github.head_ref || github.ref }} 
        
  # Check code for linting errors
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Run tests
        # Lints and formats are called only against the changed files, because other
        # files must have come from master
        run: python3 deploy/lint.sh ${{ github.head_ref || github.ref }} 

  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
      - name: Run tests
        run: python3 deploy/test.sh ${{ github.workspace }}
                    