name: merge_to_master
run-name: Merge to master

on:
  push:
    branches:
      - io-1554-test-merge # TODO change to master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run_tests:
    name: Run tests
    uses: ./.github/workflows/JOB_tests.yml

  documentation:
    name: Documentation
    uses: ./.github/workflows/JOB_generate_documentation.yml

  reverse_commit_on_fails:
    name: Reverse commit on fails
    uses: ./.github/workflows/JOB_reverse_commit_on_fails.yml


