name: created_tag
run-name: Created Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'test-*'

concurrency:
  group: created_tag
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: ${{ github.head_ref || github.ref }}

  check_master_is_passing:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Check branch is passing
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { state } } = await github.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.head_ref || github.ref }}'
            });
            //log state
            console.log(state);
            if (state !== 'success') {
              core.setFailed('Tagged branch is not passing, cannot create a release');
            }

  deploy:
    needs: [checkout, check_master_is_passing]
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { id: release_id } } = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              name: context.ref,
              draft: true,
              prerelease: context.ref.startsWith('test-')
            });
            core.setOutput('release_id', release_id);
