name: pull_request
run-name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]


# Prevent running concurrently
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  get_changed_files:
    name: Get changed files
    uses: ./.github/workflows/JOB_get_changed_files.yml


  debug:
    needs: get_changed_files
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: |
        echo "Changed files:"
        echo "${{ needs.get_changed_files.outputs.changed_files }}"
        echo "Python changed files:"
        echo "${{ needs.get_changed_files.outputs.python_changed_files }}"
        echo "Yaml changed files:"
        echo "${{ needs.get_changed_files.outputs.yaml_changed_files }}"
        echo "Json changed files:"
        echo "${{ needs.get_changed_files.outputs.json_changed_files }}"



  format:
    name: Check format of python
    needs: get_changed_files
    uses: ./.github/workflows/JOB_format.yml
    with:
      files: ${{ needs.get_changed_files.outputs.python_changed_files }}

  lint:
    name: Lint python
    needs: get_changed_files
    uses: ./.github/workflows/JOB_lint.yml
    with:
      files: ${{ needs.get_changed_files.outputs.python_changed_files }}

  run_tests:
    name: Run tests
    uses: ./.github/workflows/JOB_tests.yml

