name: merge_to_master
run-name: Merge to master

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run_tests:
    name: Run tests
    uses: ./.github/workflows/JOB_tests.yml

  documentation:
    name: Documentation
    uses: ./.github/workflows/JOB_generate_documentation.yml

  reverse_commit_on_fails:
    needs: [run_tests, documentation]
    if : ${{ failure() }}
    name: Reverse commit on fails
    uses: ./.github/workflows/JOB_debug_contexts.yml

  success: # Step for the flow to have to indicate success
    needs: [run_tests, documentation]
    if : ${{ success() }}
    name: Success
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Success"


