# Run tests
name: tests
run-name: Tests

on:
  workflow_call:

jobs:
  test:
    name: "Run Testing OS: ${{ matrix.os }} Python: ${{ matrix.python-version }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        uses: ./.github/actions/MISC_install_deps.yml

      - name: Run pytest
        shell: bash # stops windows hosts from using powershell
        run: |
          python -m pytest
