name: reverse-commit-on-fails
run-name: Reverse commit on fails

on:
  workflow_call:


# Run when master is failing due to a merge, and you want to reverse the merge
# and push the reverse commit to master.

permissions:
  contents: write

jobs:
  step-master-back-one-commit:
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    name: Step master back one commit
    runs-on: ubuntu-latest
    steps:

      - name: Checkout merge branch [${{ env.BRANCH_NAME }}]
        uses: actions/checkout@v2
        with:
          ref: $BRANCH_NAME

      - name: Reverse commit
        run: |
          git reset --hard HEAD~1
          git push origin $BRANCH_NAME --force

  recall-master-merge-flow:
    uses: ./.github/workflows/EVENT_merge_to_master.yml
