name: created_tag
run-name: Created Tag

on:
  workflow_call:
    outputs:
      release_id:
        description: The ID of the release that was created
        value: ${{ jobs.create_release.outputs.release_id }}
    inputs:
      is_draft:
        type: boolean
        description: Whether the release should be a draft
        required: false
        default: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  create_release:
    outputs:
      release_id: # Set in the JS

    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Create release
        id: create_release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { id: release_id } } = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              name: context.ref,
              draft: ${{ github.event.inputs.is_draft }},
            });
            core.setOutput('release_id', release_id);
