name: reverse-commit-on-fails
run-name: Reverse commit on fails

on:
  workflow_call:


# Run when master is failing due to a merge, and you want to reverse the merge
# and push the reverse commit to master.

jobs:

  step-master-back-one-commit:
    env:
      BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
    name: Step master back one commit
    runs-on: ubuntu-latest
    steps:

      - name: Checkout merge branch [${{ env.BRANCH_NAME }}]
        uses: actions/checkout@v2
        with:
          ref: $BRANCH_NAME

      - name: Reverse commit
        run: |
          echo "Just testing atm"
          # git reset --hard HEAD~1
          # git push origin $BRANCH_NAME --force

  # NB: This will run the parent workflow _again_ as it is a push to master
