name: typecheck
run-name: Static type analysis

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Mypy
        uses: jashparekh/mypy-action@v2
        with:
          path: '.'
          mypy_version: '1.5'
          mypy_options: '--verbose --warn-redundant-casts --warn-unused-ignores --check-untyped-defs --no-implicit-reexport --ignore-missing-imports --disallow-any-unimported --disallow-any-explicit --disallow-subclassing-any --python-version --disallow-untyped-calls --disallow-untyped-defs --disallow-incomplete-defs --no-implicit-optional --warn-unreachable --pretty'
          mypy_config_file: ''
          python_version: '3.10'
