name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: flake8 Lint
      run: |
        pip install flake8 flake8-pyproject
        success = 1
        for file in ${{ github.event.inputs.files }}
        do
          flake8 $file
          if [ $? -ne 0 ]; then
            success = 0
          fi
        done
        if [ $success -eq 0 ]; then
          exit 1
        fi
