name: lint
run-name: Check linting

on:
  workflow_call:
    inputs:
      files:
        type: string
        description: "Files to lint"
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: flake8 Lint
      shell: bash
      run: |
        pip install flake8 flake8-pyproject
        success=1
        echo "Linting files ${{ inputs.files }}"
        for file in ${{ inputs.files }}
        do
          echo "Linting $file"
          flake8 $file || success=0
        done
        if [ $success -eq 0 ]; then
          exit 1
        fi
